# ================================================== 
    #   / __ \__  ______  ____ _____ ___  (_)  __
    #  / / / / / / / __ \/ __ `/ __ `__ \/ / |/_/
    # / /_/ / /_/ / / / / /_/ / / / / / / />  <  
    #/_____/\__, /_/ /_/\__,_/_/ /_/ /_/_/_/|_|  
    #      /____/                                
    # Filename:     i3status.conf
    # Github:       https://github.com/mrrostam/dotfiles
    # Maintainer:   Pouya Rostam (Dynamix)
#================================================== 
# i3status configuration file.
# see "man i3status" for documentation.

# It is important that this file is edited as UTF-8.
# The following line should contain a sharp s:
# ß
# If the above line is not correctly displayed, fix your editor first!

general {
        output_format = "i3bar"
        colors = false
        #colors = true
        markup = pango
        interval = 10
        color_good = '#2f343f'
		color_degraded = '#ebcb8b'
		color_bad = '#ba5e57'
}

order += "load"
#order += "memory"
order += "cpu_temperature 0"
order += "disk /"
order += "disk /home"
order += "wireless _first_"
#order += "ethernet _first_"
order += "volume master"
order += "battery all"
order += "tztime local"

memory {
#        format = "<span background='#f59335'> %used </span>"
#        threshold_degraded = "1G"
#        format_degraded = "MEMORY < %available"
        format = "%used | %available"
        threshold_degraded = "1G"
        format_degraded = "MEMORY < %available"
}
wireless _first_ {
#        format_up = " (%essid|%quality) %ip"
#        format_down = "down"
        format_up = "<span background='#b48ead'>  %essid |%quality </span>"
        format_down = "<span background='#b48ead'>  Disconnected </span>"
}
ethernet _first_ {
#        format_up = "E: %ip (%speed)"
#        format_down = "E: down"
        format_up = "<span background='#88c0d0'>  %ip </span>"
        format_down = "<span background='#88c0d0'>  Disconnected </span>"
}
battery all {
#        format = "%status %percentage %remaining"
        format = "<span background='#a3be8c'> %status %percentage </span>"
        format_down = "No Battery"
        status_bat = ""
        status_chr = ""
        status_full = ""
        low_threshold = 20
        threshold_type = percentage
        integer_battery_capacity = true
        color_good = "#0000FF"
}
disk "/" {
        format = "<span background='#fec7cd'>  %free Free </span>"
}
disk "/home" {
        format = "<span background='#a1d569'>  %free Free </span>"
}
load {
        format = "<span background='#f59335'>  %5min Load </span>"
}
cpu_temperature 0 {
        format = "<span background='#bf616a'>  %degrees °C </span>"
        #path = "/sys/class/thermal/thermal_zone0/temp"
}
volume master {
        format = "<span background='#ebcb8b'>  %volume </span>"
        format_muted = "<span background='#ebcb8b'>  Muted </span>"
        device = "default"
        mixer = "Master"
        mixer_idx = 0
}
tztime local {
        #format = " %h %d, %Y %I:%M:%S"
	    format = "<span background='#81a1c1'> %time </span>"
		format_time = " %a %-d %b %H:%M"
}
