[git_commit]
only_detached = true

[hg_branch]
disabled = false

[memory_usage]
disable = false
show_percentage = true

[time]
disabled = false
format = "%T"
style = "yellow"

prompt_order = [
"username",
"hostname",
"kubernetes",
"directory",
"git_branch",
"git_commit",
"git_state",
"git_status",
"hg_branch",
"package",
"dotnet",
"elixir",
"elm",
"golang",
"haskell",
"java",
"nodejs",
"php",
"python",
"ruby",
"rust",
"terraform",
"nix_shell",
"conda",
"memory_usage",
"aws",
"env_var",
"crystal",
"cmd_duration",
"line_break",
"jobs",
"battery",
"time",
"character",
]
